name: pattern
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.1=144
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.0.1=py37h6538335_0
  - libpng=1.6.35=h2a8f88b_0
  - matplotlib=3.0.1=py37hc8f65d3_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37hdbbee80_0
  - mkl_random=1.0.1=py37h77b88f5_1
  - numpy=1.15.4=py37ha559c80_0
  - numpy-base=1.15.4=py37h8128ebf_0
  - openssl=1.0.2p=hfa6e2cd_0
  - pip=18.1=py37_0
  - pyparsing=2.3.0=py37_0
  - pyqt=5.9.2=py37h6538335_2
  - python=3.7.1=h33f27b4_4
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - qt=5.9.6=vc14h1e9a669_2
  - scikit-learn=0.20.1=py37hb854c30_0
  - scipy=1.1.0=py37h4f6bf74_1
  - setuptools=40.6.2=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.11.0=py37_1
  - sqlite=3.25.3=he774522_0
  - tornado=5.1.1=py37hfa6e2cd_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.32.3=py37_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_3
prefix: C:\ProgramData\Anaconda3\envs\pattern

